services:
  - type: web
    name: mammoai-backend
    runtime: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: UPLOAD_DIR
        value: /app/uploads

  - type: web
    name: mammoai-frontend
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://mammoai-backend-dk61.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
